'use client';
import React, {ChangeEvent, useRef, useState} from "react";
import {PackUpdateWorkerRequest, PackUpdateWorkerResponse} from './types';

const VERSION = 0.9
export default function PackUpdater() {
    const [updatedPacks, setUpdatedPacks] = useState<PackUpdateWorkerResponse[]>([]);
    const [packUpdaterMessages, setPackUpdaterMessages] = useState<string[]>([]);
    const workersCounter = useRef(0)
    const tasks = useRef<File[]>([])
    return (
        <div className={"flex gap-4"}>
            <form className={"flex flex-col gap-4"}>
                <div className={"flex gap-2"}>
                    <label className={"flex gap-2"}>
                        <input defaultChecked type={"checkbox"}/>pack name watermark <i>customizable</i>
                    </label>
                    <input placeholder={" (1.21.4)"} type={"text"}/>
                </div>

                <div className={"flex flex-col gap-2"}>
                    <label className={"flex gap-2"}>
                        <input defaultChecked type={"checkbox"}/>pack description watermark <i>customizable</i>
                    </label>
                    <input placeholder={" (generated by pvputils.vercel.app, v" + VERSION + ")"} type={"text"}/>
                </div>

                <label className={"flex gap-2"}>
                    <input defaultChecked type={"checkbox"} onChange={e =>
                        handleCheckboxHiddenVanillaDiv("generatedNetheriteConfig", e)}></input>generate netherite by recoloring pack&#39;s diamond
                </label>
                <div id={"generatedNetheriteConfig"} className={"flex gap-4"}>
                    ...
                    <div className={"flex gap-2"}>
                        <label className={"flex gap-2"}>
                            <input name={"blendMode"} defaultChecked type={"radio"}/>multiply (darker)
                        </label>
                        <label className={"flex gap-2"}>
                            <input name={"blendMode"} type={"radio"}/>overlay (lighter)
                        </label>
                    </div>
                </div>
                {/*<label className={"flex gap-2"}>*/}
                {/*    <input type={"text"}/>*/}
                {/*</label>TODO -> custom netherite colors option*/}

                <label className={"flex gap-2"}>
                    <input defaultChecked type={"checkbox"}></input>
                    remove blinking heart sprites
                </label>
                <label className={"flex gap-2"}>
                    <input defaultChecked type={"checkbox"}></input>
                    recolor wither heart sprites white
                </label>
                {/*<label className={"flex gap-2"}>*/}
                {/*    <input defaultChecked type={"checkbox"}></input>*/}
                {/*    make string red*/}
                {/*</label>TODO remove, pretty sure you can pearl through string now anyway*/}

                <label className={"flex gap-2"}>
                    <input type={"checkbox"} onChange={e =>
                        handleCheckboxHiddenVanillaDiv("hiddenBasePackUploads", e)}></input>
                    use modern base pack <span>(<a href={"https://faithfulpack.net/"} target={"_blank"} style={{ color: "blue", textDecoration: 'underline' }}>faithful</a> recommended)</span>
                </label>
                <div id={"hiddenBasePackUploads"} hidden={true} className={"flex gap-4"}>
                    ...
                    <div className={"flex flex-col gap-2"}>
                        <label className={"flex gap-2"}>
                            default
                            <input type={"file"}></input>
                        </label>
                        <label className={"flex gap-2"}>
                            if 16x16
                            <input type={"file"}></input>
                        </label>
                        <label className={"flex gap-2"}>
                            else if 32x32
                            <input type={"file"}></input>
                        </label>
                        <label className={"flex gap-2"}>
                            else if 64x64+
                            <input type={"file"}></input>
                        </label>
                        <i title={"based on grass_top.png"}>
                            updater picks from these, if present, for each pack
                        </i>
                    </div>
                </div>

                <label className={"flex gap-2"}>
                    <input type={"checkbox"}></input>
                    maintain 1.7 backwards-compatibility (larger file size)
                </label>

                <label className={"nextButton self-center"}>
                    upload (1.7.10) {/*TODO icon*/}
                    <input hidden multiple type="file" onChange={e => {
                        const packs = e.target.files;
                        if (!packs)
                            alert("invalid upload")
                        // TODO -> refresh (?)
                        else {
                            for (const pack of packs) {
                                if (workersCounter.current < 4) { // TODO -> different handling per device (?)
                                    const packName = pack.name
                                    {
                                        const worker = new Worker(new URL('./packupdateworker.ts', import.meta.url))
                                        worker.onmessage = (e: MessageEvent<PackUpdateWorkerResponse>) => {
                                            const data = e.data
                                            setUpdatedPacks(currentUpdatedPacks => [data, ...currentUpdatedPacks])
                                            setPackUpdaterMessages(current => [data.updatedPackName + " finished", ...current])
                                            const next = tasks.current.pop()
                                            if (next) {
                                                worker.postMessage(next)
                                                setPackUpdaterMessages(current => [next.name + " started", ...current])
                                            } else {
                                                worker.terminate()
                                                workersCounter.current = workersCounter.current - 1
                                            }
                                        }
                                        worker.postMessage({pack, packName} as PackUpdateWorkerRequest)
                                    }
                                    workersCounter.current = workersCounter.current + 1
                                    setPackUpdaterMessages(current => [packName + " started", ...current])
                                } else {
                                    tasks.current.push(pack)
                                    setPackUpdaterMessages(current => [pack.name + " queued", ...current])
                                }
                            }
                        }
                    }}/>
                </label>
            </form>
            <div className={"flex flex-col gap-4 grow"}>
                <ul className={"font-[family-name:var(--font-geist-mono)]"}> {/*TODO -> this scrolls and it's height is determined by updatedPacks ol height*/}
                    {packUpdaterMessages.map((message) => (
                        <li key={message}> {/*TODO -> this shouldn't remove any repeat messages*/}
                            {message}
                        </li>
                    ))}
                </ul>
            </div>
            <div className={"flex flex-col gap-4 grow"}>
                {updatedPacks.length > 0 && (
                    <button className={"nextButton"}>
                        download {updatedPacks.length}/{updatedPacks.length + workersCounter.current + tasks.current.length}
                    </button>
                )}
                <ol className={"font-[family-name:var(--font-geist-mono)]"} reversed>
                    {updatedPacks.map((pack) => (
                        <li key={pack.updatedPackName}>
                            <a href={URL.createObjectURL(pack.updatedPack)} download={pack.updatedPackName}
                               style={{color: 'blue', textDecoration: 'underline'}}>
                                {pack.updatedPackName}
                            </a>
                        </li>
                    ))}
                </ol>
                {/*TODO -> just make this a link to the bucket*/}
            </div>
        </div>
    )
}
function handleCheckboxHiddenVanillaDiv(divId: string, e: ChangeEvent<HTMLInputElement>) {
    const div = document.getElementById(divId);
    if (div)
        div.hidden = !e.target.checked;
}